modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"
issueTrackerURL = "https://example.com/issues"

[[mods]]
modId = "${mod_id}"
version = "1.0.7"
displayName = "Player links [NeoForge 1.21.1]"
authors = "acosmicnova"
description = '''${mod_description}'''

[[mixins]]
config = "playerlink.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "create"
type = "required"
versionRange = "${create_version_range}"
ordering = "AFTER"
side = "BOTH"
